[build]
target = "aarch64-unknown-linux-musl"

[env]
CXX = "/data/czy/ohos3.0/prebuilts/clang/ohos/linux-x86_64/llvm/bin/clang++"
CC = "/data/czy/ohos3.0/prebuilts/clang/ohos/linux-x86_64/llvm/bin/clang"
CFLAGS = "--sysroot=/data/czy/ohos3.0/out/release/obj/third_party/musl --target=aarch64-linux-ohosmusl"
CXXFLAGS = "--sysroot=/data/czy/ohos3.0/out/release/obj/third_party/musl --target=aarch64-linux-ohosmusl"
CXXSTDLIB = "c++"

[target.aarch64-unknown-linux-musl]
linker = "/home/hit/OHOS_3.0_LTS/harmony/prebuilts/clang/ohos/linux-x86_64/llvm/bin/ld.lld"

rustflags = [
    "-Ctarget-feature=-crt-static",
    "-Clink-self-contained=off",
    "-L/data/czy/ohos3.0/out/release/obj/third_party/musl/usr/lib/aarch64-linux-ohosmusl",
    "-L/data/czy/ohos3.0/prebuilts/clang/ohos/linux-x86_64/llvm/lib/aarch64-linux-ohosmusl",
    "-L/data/czy/ohos3.0/prebuilts/clang/ohos/linux-x86_64/llvm/lib/aarch64-linux-ohosmusl/c++",
    "-L/data/czy/ohos3.0/prebuilts/clang/ohos/linux-x86_64/llvm/lib"
]

# "-Cembed-bitcode=yes",
#    "-Clink-arg=--gc-sections",
#    "-Clto",

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "std", "panic_unwind"]
build-std-features = ["llvm-libunwind"]
